[project]
name = "stark-bank-challenge"
version = "0.1.0"
description = "Integração com o Sandbox do Stark Bank: emissão de Invoices e Transfer do valor líquido"
authors = [
    {name = "Gabriel Cardoso",email = "gabrielsilva22012@hotmail.com"}
]
readme = "README.md"
requires-python = "^3.12"
dependencies = [
    "starkbank (>=2.35.0,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "faker (>=40.36.0,<41.0.0)",
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.52.3,<0.53.0)",
    "confluent-kafka (>=2.15.0,<3.0.0)"
]


[tool.poetry]
# aplicação, não biblioteca: não há pacote para instalar
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "httpx2 (>=2.10.0,<3.0.0)"
]
